sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                webgriffe_bisn_add_subscription: '@WebgriffeSyliusBackInStockNotificationPlugin/_addSubscription.html.twig'
        sylius.shop.product.show.add_to_cart_form:
            blocks:
                webgriffe_bisn_add_subscription: '@WebgriffeSyliusBackInStockNotificationPlugin/_configurableButton.html.twig'
        sylius.shop.layout.after_body:
            blocks:
                webgriffe_bisn_add_javascript: '@WebgriffeSyliusBackInStockNotificationPlugin/_javascript.html.twig'
