sylius_mailer:
    emails:
        webgriffe_back_in_stock_notification_success_subscription:
            template: "@WebgriffeSyliusBackInStockNotificationPlugin/Email/successSubscription.html.twig"
        webgriffe_back_in_stock_notification_alert:
            template: "@WebgriffeSyliusBackInStockNotificationPlugin/Email/notificationAlert.html.twig"
