webgriffe_back_in_stock_notification_add_subscription_admin:
    resource: "@WebgriffeSyliusBackInStockNotificationPlugin/config/routing/admin_routing.yaml"
    prefix: '/%sylius_admin.path_name%'

webgriffe_back_in_stock_notification_add_subscription_shop:
    resource: "@WebgriffeSyliusBackInStockNotificationPlugin/config/routing/shop_routing.yaml"
