services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Controller\:
        resource: ../src/Controller/
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Controller\SubscriptionController:
        arguments:
            $backInStockNotificationFactory: '@webgriffe.factory.back_in_stock_notification_subscription'
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Command\:
        resource: ../src/Command/
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Repository\SubscriptionRepositoryInterface:
        alias: webgriffe.repository.back_in_stock_notification_subscription
        public: false
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Menu\AccountMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addMenuItems }
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Twig\AvailabilityExtension:
        tags:
            - { name: twig.extension }
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Twig\AvailabilityRuntime:
        arguments:
            - '@sylius.availability_checker.default'
        tags:
            - { name: twig.runtime }
    
    Webgriffe\SyliusBackInStockNotificationPlugin\Validator\SubscriptionUniqueValidator:
        arguments:
            - '@webgriffe.repository.back_in_stock_notification_subscription'
            - '@sylius.repository.product_variant'
            - '@sylius.context.customer'
        tags:
            - { name: validator.constraint_validator }
